#+TITLE: Mauris ac felis vel velit tristique imperdiet.
#+date: 2011-10-10

#+BEGIN_HTML
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
    <span class="sr-only">100% Complete</span>
  </div>
</div>
#+END_HTML

* Vestibulum convallis, lorem a tempus semper, dui dui euismod elit, vitae placerat urna tortor vitae lacus.

  [[http://google.com][Here's a hella awsum link to teh google]]

  Nullam eu ante vel est convallis dignissim.  Fusce suscipit, wisi nec
  facilisis facilisis, est dui fermentum leo, quis tempor ligula erat quis odio.
  Nunc porta vulputate tellus.  Nunc rutrum turpis sed pede.  Sed bibendum.
  Aliquam posuere.  Nunc aliquet, augue nec adipiscing interdum, lacus tellus
  malesuada massa, quis varius mi purus non odio.  Pellentesque condimentum,
  magna ut suscipit hendrerit, ipsum augue ornare nulla, non luctus diam neque
  sit amet urna.  Curabitur vulputate vestibulum lorem.  Fusce sagittis, libero
  non molestie mollis, magna orci ultrices dolor, at vulputate neque nulla
  lacinia eros.  Sed id ligula quis est convallis tempor.  Curabitur lacinia
  pulvinar nibh.  Nam a sapien.

* R

#+BEGIN_SRC R
print("hello from r")
#+END_SRC

* scala

#+BEGIN_SRC scala
println("hello from scala")
#+END_SRC
